namespace FluentVault;

public enum SearchStringProperty : long
{
    Classification = 1,
    Comment = 3,
    CreatedBy = 6,
    FileName = 9,
    FileNameHistorical = 10,
    CheckedOutLocalSpec = 15,
    CheckedOutMachine = 16,
    CheckedOutBy = 18,
    ChangeOrderState = 22,
    VisualizationAttachment = 23,
    Originator = 24,
    Provider = 27,
    iLogicRuleStatus = 28,
    FolderPath = 29,
    Name = 30,
    TargetEntityClass = 31,
    ParentEntityClass = 32,
    FileExtension = 33,
    InitialApprover = 41,
    CategoryName = 43,
    CategoryNameHistorical = 44,
    LifecycleDefinition = 47,
    LifecycleDefinitionHistorical = 48,
    State = 49,
    StateHistorical = 50,
    RevisionScheme = 51,
    RevisionSchemeHistorical = 52,
    Revision = 53,
    LastUpdatedBy = 57,
    Number = 58,
    TitleItemCO = 59,
    Units = 60,
    DescriptionItemCO = 61,
    Installation = 62,
    Location = 63,
    Tag = 64,
    SubmittedBy = 66,
    SubjectCO = 71,
    Message = 72,
    CustomObjectName = 74,
    CustomObjectSystemName = 75,
    LatestApprover = 241,
}
